### ISSUE TITLE
Xhprof output just displays file

### ISSUE THREAD

**Issue by anotherjames** [computerminds/parrot#129] opened 2016-07-19 11:39 UTC
i.e. on visiting http://localhost/xhprof/index.php, my browser just shows me the contents of that file rather than running the PHP!

**Comment by darthsteven** [comment] 2016-07-19 12:48
What version (git commit) of parrot are you using?

**Comment by anotherjames** [comment] 2016-07-19 12:49
I'm currently on c4e30a8d3775e6c68cc211fc94b76da5d0251f10 on trusty.

**Comment by anotherjames** [comment] 2016-07-19 12:50
Oh, am I just out of date?

**Comment by darthsteven** [comment] 2016-07-19 12:53
Yeah, sort of, xhprof is removed at the moment, adding it back in #124 and probably need to resolve phpMyAdmin too in #120

**Comment by darthsteven** [comment] 2016-07-19 12:54
Yeah, so I think this issue is just a duplicate of #120.

**Closed by darthsteven** 2016-07-19 12:54 UTC
