### ISSUE TITLE
[trusty] do we need mod-php for phpmyadmin and xhprof?

### ISSUE THREAD

**Issue by finnlewis** [computerminds/parrot#120] opened 2016-01-20 23:35 UTC
Hi guys,
I'm liking the trusty branch, and have forked it over at https://github.com/agilecollective/parrot/tree/trusty to allow us to add our gulp based sass compilation gubbins, which is working so far.
I couldn't get XHProf working, and then had similar issues with PHPMyAdmin, which I realise is due to the default config files being geared for mod-php rather than php-fpm. 
After some trial and error with php-fpm config, I installed mod-php in the box and suddenly the XHProf started working for me, and PHPMyAdmin.
So does having mod-php installed cause any performance or other issues? If not, is that the path of least resistance? If so, can anyone help with config for XHProf and PHPMyAdmin on php-fpm?
Cheers,
Finn

**Comment by darthsteven** [comment] 2016-01-21 08:34
I'd like to avoid mod-php because using php-fpm should eventually allow things like supporting multiple concurrent versions of PHP using something like phpenv.

That being said, if we've broken XHProf and PHPMyAdmin, that's a serious regression we should sort :)

**Comment by darthsteven** [comment] 2017-06-07 09:49
We should fix this so that xhprof is useful again!

**Comment by darthsteven** [comment] 2017-06-07 13:12
This was fixed in #136 for both xhprof and phpmyadmin

**Closed by darthsteven** 2017-06-07 13:12 UTC
Labels: bug
